import type { WorkspaceLocale } from "./types";

const en = {
  title: "Workspace",
  description: "Interactive SSH terminal and files",
  modes: { terminal: "Terminal", files: "Files", split: "Split", transfers: "Transfers" },
  host: "Host",
  selectHost: "Select a host",
  localFiles: "Local files",
  localFilesHint: "Select a host to browse remote files. In Split, opening a terminal connects Files to the same host.",
  newTerminal: "New terminal",
  noHosts: "Add an SSH host before opening Workspace.",
  noTerminal: "Choose a host to open an interactive terminal.",
  terminalTabs: "Terminal tabs",
  resizeWorkspacePanes: "Resize Files and Terminal panes",
  closeTerminal: "Close terminal",
  reconnect: "Reconnect",
  searchTerminal: "Search terminal",
  searchPlaceholder: "Find in terminal",
  previousMatch: "Previous match",
  nextMatch: "Next match",
  closeSearch: "Close search",
  pasteTitle: "Send pasted text?",
  pasteBody: "The pasted text contains multiple lines or more than 4 KiB and may execute commands.",
  sendPaste: "Send",
  cancel: "Cancel",
  connected: "Connected",
  connecting: "Connecting",
  reconnecting: "Reconnecting",
  disconnected: "Disconnected",
  closing: "Closing",
  closed: "Closed",
  failed: "Failed",
  terminalUnavailable: "Terminal renderer could not be loaded.",
  filesUnavailable: "Files could not connect to this SSH host.",
  back: "Back",
  forward: "Forward",
  up: "Up",
  home: "Home",
  refresh: "Refresh",
  location: "Remote path",
  sortBy: "Sort by",
  sortName: "Name",
  sortType: "Type",
  sortSize: "Size",
  sortModified: "Modified",
  ascending: "Ascending",
  descending: "Descending",
  searchFiles: "Filter or search files",
  recursiveSearch: "Press Enter for recursive search",
  stopSearch: "Stop search",
  showHidden: "Show hidden",
  hideHidden: "Hide hidden",
  upload: "Upload",
  download: "Download",
  newFolder: "New folder",
  emptyDirectory: "This directory is empty.",
  fileName: "Name",
  fileType: "Type",
  fileSize: "Size",
  fileModified: "Modified",
  directory: "Directory",
  file: "File",
  symlink: "Link",
  other: "Other",
  open: "Open",
  preview: "Preview",
  rename: "Rename",
  delete: "Delete",
  copyPath: "Copy path",
  openTerminalHere: "Open terminal here",
  terminalHereUnavailable: "Opening a shell in this directory is not available from the connected backend.",
  uploadHere: "Upload here",
  loadMore: "Load more",
  resultsTruncated: "Results are limited by the backend safety cap.",
  scanned: "scanned",
  followCwd: "Follow terminal directory",
  followCwdPaused: "Following paused after manual navigation.",
  locateTerminal: "Locate terminal directory",
  cwdUnavailable: "The terminal directory is not verified for this host.",
  operationTitle: "Confirm remote file operation",
  operationExpires: "This preview expires shortly. The backend will re-check the target before changing it.",
  confirmOperation: "Confirm operation",
  backup: "Recovery backup",
  destinationName: "Destination name",
  folderName: "Folder name",
  invalidName: "Enter a valid name without a slash.",
  previewTitle: "File preview",
  previewBlocked: "Preview is blocked by the backend safety policy.",
  noPreview: "No safe preview is available.",
  close: "Close",
  transfersEmpty: "No transfers yet.",
  transfer: "Transfer",
  source: "Source",
  destination: "Destination",
  progress: "Progress",
  speed: "Speed",
  eta: "ETA",
  attempt: "Attempt",
  status: "Status",
  actions: "Actions",
  pause: "Pause",
  resume: "Resume",
  retry: "Retry",
  restart: "Restart",
  cancelTransfer: "Cancel",
  conflictTitle: "Resolve destination conflict",
  conflictBody: "The destination changed or already exists. Choose how this transfer should continue.",
  skip: "Skip",
  keepBoth: "Keep both",
  replaceWithBackup: "Replace with backup",
  applyToBatch: "Apply to matching conflicts in this batch",
  failureDetails: "Failure details",
  errorCode: "Error code",
  resumeOffset: "Resume offset",
  fingerprint: "Fingerprint",
  viewTask: "View task",
  recoveries: "Recovery backups",
  recoveriesEmpty: "No recovery backups.",
  localRecoveries: "Local download backups",
  localRecoveriesEmpty: "No local download backups.",
  localDownloadReplacement: "Download replacement",
  localPurgeBody: "Inspect the restored or replaced local file first. This permanently removes the local recovery copy.",
  recoveryReady: "A recovery backup is available for this file change.",
  viewRecovery: "View recovery",
  restore: "Restore",
  purge: "Permanently delete backup",
  purgeTitle: "Permanently delete recovery backup?",
  purgeBody: "Inspect the restored or replaced files first. This permanently removes the recovery copy.",
  confirmPurge: "Delete backup permanently",
  loading: "Loading…",
  busy: "Working…",
  error: "Workspace operation failed",
  retryLoad: "Retry",
  unknown: "Unknown",
  seconds: "s"
};

export type WorkspaceCopy = typeof en;

const zh: WorkspaceCopy = {
  title: "工作台",
  description: "交互式 SSH 终端与文件管理",
  modes: { terminal: "终端", files: "文件", split: "分屏", transfers: "传输" },
  host: "主机",
  selectHost: "选择主机",
  localFiles: "本地文件",
  localFilesHint: "选择主机以浏览远端文件；分屏中新建终端后，文件页会自动连接同一主机。",
  newTerminal: "新建终端",
  noHosts: "请先添加 SSH 主机，再打开工作台。",
  noTerminal: "选择主机以打开交互式终端。",
  terminalTabs: "终端标签页",
  resizeWorkspacePanes: "调整文件与终端面板大小",
  closeTerminal: "关闭终端",
  reconnect: "重新连接",
  searchTerminal: "搜索终端",
  searchPlaceholder: "在终端中查找",
  previousMatch: "上一个匹配项",
  nextMatch: "下一个匹配项",
  closeSearch: "关闭搜索",
  pasteTitle: "发送粘贴内容？",
  pasteBody: "粘贴内容包含多行或超过 4 KiB，可能直接执行命令。",
  sendPaste: "发送",
  cancel: "取消",
  connected: "已连接",
  connecting: "连接中",
  reconnecting: "重连中",
  disconnected: "已断开",
  closing: "关闭中",
  closed: "已关闭",
  failed: "失败",
  terminalUnavailable: "无法加载终端渲染器。",
  filesUnavailable: "无法连接到此 SSH 主机的文件会话。",
  back: "后退",
  forward: "前进",
  up: "上级",
  home: "主目录",
  refresh: "刷新",
  location: "远端路径",
  sortBy: "排序",
  sortName: "名称",
  sortType: "类型",
  sortSize: "大小",
  sortModified: "修改时间",
  ascending: "升序",
  descending: "降序",
  searchFiles: "筛选或搜索文件",
  recursiveSearch: "按 Enter 递归搜索",
  stopSearch: "停止搜索",
  showHidden: "显示隐藏项",
  hideHidden: "隐藏隐藏项",
  upload: "上传",
  download: "下载",
  newFolder: "新建文件夹",
  emptyDirectory: "此目录为空。",
  fileName: "名称",
  fileType: "类型",
  fileSize: "大小",
  fileModified: "修改时间",
  directory: "目录",
  file: "文件",
  symlink: "链接",
  other: "其他",
  open: "打开",
  preview: "预览",
  rename: "重命名",
  delete: "删除",
  copyPath: "复制路径",
  openTerminalHere: "在此处打开终端",
  terminalHereUnavailable: "当前已连接后端不支持在此目录启动 Shell。",
  uploadHere: "上传到此处",
  loadMore: "加载更多",
  resultsTruncated: "结果已达到后端安全上限。",
  scanned: "已扫描",
  followCwd: "跟随终端目录",
  followCwdPaused: "手动导航后已暂停跟随。",
  locateTerminal: "定位到终端目录",
  cwdUnavailable: "此主机的终端目录尚未通过验证。",
  operationTitle: "确认远端文件操作",
  operationExpires: "此预览将在短时间后过期。后端会在变更前再次核验目标。",
  confirmOperation: "确认操作",
  backup: "恢复备份",
  destinationName: "目标名称",
  folderName: "文件夹名称",
  invalidName: "请输入不含斜杠的有效名称。",
  previewTitle: "文件预览",
  previewBlocked: "后端安全策略已阻止预览。",
  noPreview: "没有可安全显示的预览。",
  close: "关闭",
  transfersEmpty: "暂无传输任务。",
  transfer: "传输",
  source: "来源",
  destination: "目标",
  progress: "进度",
  speed: "速度",
  eta: "预计剩余",
  attempt: "尝试次数",
  status: "状态",
  actions: "操作",
  pause: "暂停",
  resume: "继续",
  retry: "重试",
  restart: "重新开始",
  cancelTransfer: "取消",
  conflictTitle: "处理目标冲突",
  conflictBody: "目标已存在或发生变化。请选择本次传输的处理方式。",
  skip: "跳过",
  keepBoth: "两者保留",
  replaceWithBackup: "备份后覆盖",
  applyToBatch: "应用到本批次的同类冲突",
  failureDetails: "失败详情",
  errorCode: "错误代码",
  resumeOffset: "续传位置",
  fingerprint: "指纹状态",
  viewTask: "查看任务",
  recoveries: "恢复备份",
  recoveriesEmpty: "暂无恢复备份。",
  localRecoveries: "本地下载备份",
  localRecoveriesEmpty: "暂无本地下载备份。",
  localDownloadReplacement: "下载覆盖",
  localPurgeBody: "请先检查恢复或替换后的本地文件。此操作会永久删除本地恢复副本。",
  recoveryReady: "此文件变更已创建可恢复备份。",
  viewRecovery: "查看恢复备份",
  restore: "恢复",
  purge: "永久删除备份",
  purgeTitle: "永久删除恢复备份？",
  purgeBody: "请先检查恢复或替换后的文件。此操作会永久删除恢复副本。",
  confirmPurge: "永久删除备份",
  loading: "加载中…",
  busy: "处理中…",
  error: "工作台操作失败",
  retryLoad: "重试",
  unknown: "未知",
  seconds: "秒"
};

export const workspaceCopy: Record<WorkspaceLocale, WorkspaceCopy> = { en, zh };
