import type { WorkspaceLocale, WorkspaceTransferState } from "../types";

const en = {
  title: "Transfers",
  description: "Manage cross-host uploads, downloads, and recovery tasks",
  refresh: "Refresh",
  newTransfer: "New transfer",
  today: "Today",
  active: "In progress",
  completed: "Completed",
  failed: "Failed / retry",
  throughput: "Current throughput",
  transferred: "transferred",
  averageSpeed: "Average speed",
  successRate: "Success rate",
  needsAttention: "need attention",
  liveAggregate: "Live aggregate speed",
  allDirections: "All tasks",
  uploads: "Uploads",
  downloads: "Downloads",
  allStatuses: "All statuses",
  clearFilters: "Clear filters",
  searchPlaceholder: "Search source, destination, or host",
  pageSize: "per page",
  previousPage: "Previous page",
  nextPage: "Next page",
  page: "Page",
  of: "of",
  results: "tasks",
  noMatches: "No transfers match the current filters.",
  restoreBackups: "Recovery backups",
  restoreBackupsHint: "Restore protected copies created before remote file changes.",
  localBackups: "Local download backups",
  localBackupsHint: "Restore local files replaced by completed downloads.",
  recentTransfers: "Recent transfers",
  recentTransfersHint: "Latest activity across connected hosts.",
  supportDetails: "Backups and recent transfers",
  expandSupportDetails: "Expand backups and recent transfers",
  collapseSupportDetails: "Collapse backups and recent transfers",
  noRecent: "No recent transfers.",
  backupPath: "Backup",
  createdAt: "Created",
  moreActions: "More actions",
  progressLabel: "Transfer progress",
  directionUpload: "Upload",
  directionDownload: "Download",
  status: {
    queued: "Queued",
    running: "Running",
    pausing: "Pausing",
    paused: "Paused",
    "waiting-conflict": "Needs decision",
    verifying: "Verifying",
    finalizing: "Finalizing",
    completed: "Completed",
    failed: "Failed",
    cancelled: "Cancelled",
    interrupted: "Interrupted"
  } satisfies Record<WorkspaceTransferState, string>
};

export type TransferUiCopy = typeof en;

const zh: TransferUiCopy = {
  title: "传输",
  description: "管理跨主机上传、下载与恢复任务",
  refresh: "刷新",
  newTransfer: "新建传输任务",
  today: "今日传输",
  active: "进行中",
  completed: "已完成",
  failed: "失败 / 重试",
  throughput: "当前吞吐",
  transferred: "已传输",
  averageSpeed: "平均速度",
  successRate: "成功率",
  needsAttention: "个待处理",
  liveAggregate: "实时任务速度合计",
  allDirections: "全部任务",
  uploads: "上传",
  downloads: "下载",
  allStatuses: "全部状态",
  clearFilters: "清除筛选",
  searchPlaceholder: "搜索来源、目标或主机",
  pageSize: "条 / 页",
  previousPage: "上一页",
  nextPage: "下一页",
  page: "第",
  of: "页，共",
  results: "条任务",
  noMatches: "没有符合当前筛选条件的传输任务。",
  restoreBackups: "恢复备份",
  restoreBackupsHint: "恢复远端文件变更前创建的受保护副本。",
  localBackups: "本地下载备份",
  localBackupsHint: "恢复下载任务覆盖前的本地文件。",
  recentTransfers: "最近传输",
  recentTransfersHint: "查看已连接主机的最新传输活动。",
  supportDetails: "备份与最近传输",
  expandSupportDetails: "展开备份与最近传输",
  collapseSupportDetails: "收起备份与最近传输",
  noRecent: "暂无最近传输。",
  backupPath: "备份位置",
  createdAt: "创建时间",
  moreActions: "更多操作",
  progressLabel: "传输进度",
  directionUpload: "上传",
  directionDownload: "下载",
  status: {
    queued: "排队中",
    running: "进行中",
    pausing: "暂停中",
    paused: "已暂停",
    "waiting-conflict": "等待处理",
    verifying: "校验中",
    finalizing: "收尾中",
    completed: "已完成",
    failed: "失败",
    cancelled: "已取消",
    interrupted: "已中断"
  }
};

export const transferUiCopy: Record<WorkspaceLocale, TransferUiCopy> = { en, zh };
