import type { WorkspaceLocale } from "../types";

const en = {
  directoryTree: "Directory tree",
  rootDirectory: "Root directory",
  quickAccess: "Quick access",
  homeDirectory: "Home",
  currentDirectory: "Current directory",
  expandDirectory: "Expand directory",
  collapseDirectory: "Collapse directory",
  resizeDirectoryTree: "Resize directory tree",
  resizeColumn: "Resize column",
  showTree: "Show directory tree",
  hideTree: "Hide directory tree",
  showDetails: "Show file details",
  hideDetails: "Hide file details",
  sftpConnected: "SFTP connected",
  localConnected: "Local files ready",
  tableView: "List view",
  selectAllPage: "Select all files on this page",
  clearPageSelection: "Clear this page selection",
  selectEntry: "Select",
  permissions: "Permissions",
  owner: "Owner",
  ownerUid: "Owner UID",
  ownerGid: "Group GID",
  details: "Details",
  activity: "Activity",
  noSelection: "Select a file or folder to inspect its details.",
  selectedItems: "items selected",
  path: "Path",
  modified: "Modified",
  size: "Size",
  type: "Type",
  openTerminal: "Open in terminal",
  moreActions: "More actions",
  pagination: "File list pagination",
  previousPage: "Previous page",
  nextPage: "Next page",
  page: "Page",
  of: "of",
  rowsPerPage: "Rows per page",
  loadedItems: "loaded items",
  selected: "selected",
  unknownOwner: "—",
  closePanel: "Close panel"
};

type FilesUiCopyShape = { [Key in keyof typeof en]: string };

const zh: FilesUiCopyShape = {
  directoryTree: "目录树",
  rootDirectory: "根目录",
  quickAccess: "快捷访问",
  homeDirectory: "主目录",
  currentDirectory: "当前目录",
  expandDirectory: "展开目录",
  collapseDirectory: "折叠目录",
  resizeDirectoryTree: "调整目录树宽度",
  resizeColumn: "调整列宽",
  showTree: "显示目录树",
  hideTree: "隐藏目录树",
  showDetails: "显示文件详情",
  hideDetails: "隐藏文件详情",
  sftpConnected: "SFTP 已连接",
  localConnected: "本地文件已就绪",
  tableView: "列表视图",
  selectAllPage: "选择本页全部文件",
  clearPageSelection: "清除本页选择",
  selectEntry: "选择",
  permissions: "权限",
  owner: "所有者",
  ownerUid: "所有者 UID",
  ownerGid: "用户组 GID",
  details: "详情",
  activity: "活动",
  noSelection: "选择文件或文件夹以查看详细信息。",
  selectedItems: "项已选择",
  path: "路径",
  modified: "修改时间",
  size: "大小",
  type: "类型",
  openTerminal: "在终端中打开",
  moreActions: "更多操作",
  pagination: "文件列表分页",
  previousPage: "上一页",
  nextPage: "下一页",
  page: "第",
  of: "/",
  rowsPerPage: "每页行数",
  loadedItems: "个已加载项目",
  selected: "已选择",
  unknownOwner: "—",
  closePanel: "关闭面板"
};

export const filesUiCopy: Record<WorkspaceLocale, FilesUiCopyShape> = { en, zh };
export type FilesUiCopy = FilesUiCopyShape;
